/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidades.clsAlquilerServicio;
import accesoDatos.clsAlquilerServicioAD;
import accesoDatos.clsServicioNubeAD;
import accesoDatos.clsUsuarioAD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ivans
 */
public class dlgAlquiler extends javax.swing.JDialog {

    /**
     * Creates new form dlgAlquiler
     */
    DefaultTableModel modelo;
    String[] titulos = {"ID", "Nombre", "Duracion", "Inicio", "Fin"};

    public dlgAlquiler(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo = new DefaultTableModel(null, titulos);
        tblDatos.setModel(modelo);

        limpiar();
        btnAlquilar.setEnabled(false);
        mostrarServicio();

    }

    private void mostrarServicio() {

        clsServicioNubeAD servicios = new clsServicioNubeAD();
        for (String nombreServicio : servicios.mostrarServicio()) {
            cboTipoServicio.addItem(nombreServicio);
        }

    }

    private void limpiar() {
        txtDuracion.setText("");
        txtFechaFinal.setText("");
        txtFechaInicio.setText("");
        txtID.setText("");

        btnAlquilar.setEnabled(true);
        btnModificar.setEnabled(false);
    }

    private String getNombreServicioByServicioId(int servicioId) {
        clsServicioNubeAD serviciosAD = new clsServicioNubeAD();
        return serviciosAD.getNombreServicioByServicioId(servicioId);
    }

    private void cargarDatos(int user_id) {

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        ArrayList<clsAlquilerServicio> lista;
        clsAlquilerServicioAD servicioAD = new clsAlquilerServicioAD();

        try {
            lista = servicioAD.listado(user_id);
            for (clsAlquilerServicio servicio : lista) {
                String fila[] = {servicio.getIdAlquiler() + "", getNombreServicioByServicioId(servicio.getServicio_id()), servicio.getTiempoDeServicio() + "", servicio.getFechaInicio(), servicio.getFechaFinal()};
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            btnNuevo = new javax.swing.JButton();
            jPanel1 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            txtID = new javax.swing.JTextField();
            txtDuracion = new javax.swing.JTextField();
            txtFechaInicio = new javax.swing.JTextField();
            txtFechaFinal = new javax.swing.JTextField();
            jLabel6 = new javax.swing.JLabel();
            txtEmail = new javax.swing.JTextField();
            jLabel7 = new javax.swing.JLabel();
            cboTipoServicio = new javax.swing.JComboBox<>();
            btnAlquilar = new javax.swing.JButton();
            btnModificar = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            tblDatos = new javax.swing.JTable();
            btnBuscar = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

            btnNuevo.setBackground(new java.awt.Color(102, 255, 102));
            btnNuevo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            btnNuevo.setForeground(new java.awt.Color(0, 204, 51));
            btnNuevo.setText("Nuevo");
            btnNuevo.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnNuevoActionPerformed(evt);
                  }
            });

            jPanel1.setBackground(new java.awt.Color(153, 204, 255));

            jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(0, 204, 0));
            jLabel2.setText("ID del servicio: ");

            jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(0, 204, 0));
            jLabel3.setText("Duración :");

            jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(0, 204, 0));
            jLabel4.setText("Inicio :");

            jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(0, 204, 0));
            jLabel5.setText("Fin :");

            txtID.setEditable(false);
            txtID.setEnabled(false);

            txtFechaFinal.setEditable(false);

            jLabel6.setText("Email:");

            jLabel7.setText("Tipo de Servicio: ");

            cboTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONAR--" }));

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(jLabel7)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                          .addGap(32, 32, 32)
                                          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel4)
                                                            .addComponent(jLabel3)
                                                            .addComponent(jLabel5))
                                                      .addGap(11, 11, 11))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jLabel2))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                              .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(txtDuracion, javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(txtFechaInicio)
                              .addComponent(txtFechaFinal)
                              .addComponent(txtEmail)
                              .addComponent(cboTipoServicio, 0, 155, Short.MAX_VALUE))
                        .addContainerGap(18, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel6)
                              .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(cboTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel3)
                              .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel4)
                              .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel5))
                        .addContainerGap())
            );

            btnAlquilar.setBackground(new java.awt.Color(102, 255, 102));
            btnAlquilar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            btnAlquilar.setForeground(new java.awt.Color(0, 204, 51));
            btnAlquilar.setText("Alquilar");
            btnAlquilar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnAlquilarActionPerformed(evt);
                  }
            });

            btnModificar.setBackground(new java.awt.Color(102, 255, 102));
            btnModificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            btnModificar.setForeground(new java.awt.Color(0, 204, 51));
            btnModificar.setText("Modificar");
            btnModificar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnModificarActionPerformed(evt);
                  }
            });

            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(0, 153, 204));
            jLabel1.setText("MANTENIMIENTO DE ALQUILER");

            tblDatos.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                  },
                  new String [] {
                        "ID", "Duración", "Inicio", "Fin"
                  }
            ));
            tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        tblDatosMouseClicked(evt);
                  }
            });
            jScrollPane1.setViewportView(tblDatos);

            btnBuscar.setBackground(new java.awt.Color(102, 255, 102));
            btnBuscar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            btnBuscar.setForeground(new java.awt.Color(0, 204, 51));
            btnBuscar.setText("Buscar");
            btnBuscar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnBuscarActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1)
                                    .addContainerGap())
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(btnAlquilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                          .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                                    .addContainerGap())
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addGap(59, 59, 59))))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAlquilar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

    private int getUserIdByEmail() {
        String email = txtEmail.getText();
        clsUsuarioAD usuario = new clsUsuarioAD();
        return usuario.getIdByEmail(email);
    }

    private int getServicioIdByName() {
        String servicio = cboTipoServicio.getSelectedItem().toString();
        clsServicioNubeAD servicioAD = new clsServicioNubeAD();
        return servicioAD.getServicioIdByNombre(servicio);
    }

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilarActionPerformed
        // TODO add your handling code here:
        int user_id = getUserIdByEmail();

        int duracion = Integer.parseInt(txtDuracion.getText());
        String fechaInicial = txtFechaInicio.getText();

        int servicioId = getServicioIdByName();

        clsAlquilerServicio alquilerServicio = new clsAlquilerServicio(duracion, fechaInicial, servicioId, user_id);
        clsAlquilerServicioAD conexion = new clsAlquilerServicioAD();
        conexion.agregar(alquilerServicio);

        cargarDatos(user_id);
    }//GEN-LAST:event_btnAlquilarActionPerformed

      private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
          // TODO add your handling code here:
          int user_id = getUserIdByEmail();
          int idAlquiler = Integer.parseInt(txtID.getText());
          int duracion = Integer.parseInt(txtDuracion.getText());
          String fechaInicial = txtFechaInicio.getText();

          int servicioId = getServicioIdByName();

          clsAlquilerServicio alquilerServicio = new clsAlquilerServicio(idAlquiler, duracion, fechaInicial, servicioId, user_id);
          clsAlquilerServicioAD conexion = new clsAlquilerServicioAD();
          conexion.modificar(alquilerServicio);

          cargarDatos(user_id);

      }//GEN-LAST:event_btnModificarActionPerformed

      private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
          // TODO add your handling code here:
          int filaSel = tblDatos.getSelectedRow();

          txtID.setText(modelo.getValueAt(filaSel, 0).toString());
          cboTipoServicio.setSelectedItem(modelo.getValueAt(filaSel, 1).toString());
          txtDuracion.setText(modelo.getValueAt(filaSel, 2).toString());

          txtFechaInicio.setText(modelo.getValueAt(filaSel, 3).toString());
          txtFechaFinal.setText(modelo.getValueAt(filaSel, 4).toString());

          btnAlquilar.setEnabled(false);
          btnModificar.setEnabled(true);

      }//GEN-LAST:event_tblDatosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int userId = getUserIdByEmail();
        cargarDatos(userId);
        limpiar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgAlquiler dialog = new dlgAlquiler(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btnAlquilar;
      private javax.swing.JButton btnBuscar;
      private javax.swing.JButton btnModificar;
      private javax.swing.JButton btnNuevo;
      private javax.swing.JComboBox<String> cboTipoServicio;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JTable tblDatos;
      private javax.swing.JTextField txtDuracion;
      private javax.swing.JTextField txtEmail;
      private javax.swing.JTextField txtFechaFinal;
      private javax.swing.JTextField txtFechaInicio;
      private javax.swing.JTextField txtID;
      // End of variables declaration//GEN-END:variables
}
