/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidades.clsServicioNube;
import accesoDatos.clsServicioNubeAD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ivans
 */
public class dlgServicio extends javax.swing.JDialog {

      /**
       * Creates new form dlgServicio
       */
      DefaultTableModel modelo;
      String[] titulos = {"ID servicio", "Nombre", "Precio"};

      public dlgServicio(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            initComponents();
            modelo = new DefaultTableModel(null, titulos);
            tblDatos.setModel(modelo);
            cargarDatos();
      }

      private void cargarDatos() {

            while (modelo.getRowCount() > 0) {
                  modelo.removeRow(0);
            }

            ArrayList<clsServicioNube> lista;
            clsServicioNubeAD servicioAD = new clsServicioNubeAD();

            try {
                  lista = servicioAD.listado();
                  for (clsServicioNube servicio : lista) {
                        String fila[] = {servicio.getIdServicio() + "", servicio.getNombre(), servicio.getPrecio() + ""};
                        modelo.addRow(fila);
                  }
            } catch (Exception e) {
                  JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }

            btnGuardar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnNuevo.setEnabled(true);

      }

      private void Limpiar() {
            txtID.setText("");
            txtPrecio.setText("");
            txtTipoServicio.setText("");

            btnGuardar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnNuevo.setEnabled(true);
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            btnGuardar = new javax.swing.JButton();
            btnModificar = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            tblDatos = new javax.swing.JTable();
            jLabel1 = new javax.swing.JLabel();
            btnNuevo = new javax.swing.JButton();
            jPanel1 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            txtID = new javax.swing.JTextField();
            txtPrecio = new javax.swing.JTextField();
            txtTipoServicio = new javax.swing.JTextField();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

            btnGuardar.setBackground(new java.awt.Color(102, 255, 102));
            btnGuardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            btnGuardar.setForeground(new java.awt.Color(0, 204, 51));
            btnGuardar.setText("Guardar");
            btnGuardar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnGuardarActionPerformed(evt);
                  }
            });

            btnModificar.setBackground(new java.awt.Color(102, 255, 102));
            btnModificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            btnModificar.setForeground(new java.awt.Color(0, 204, 51));
            btnModificar.setText("Modificar");
            btnModificar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnModificarActionPerformed(evt);
                  }
            });

            tblDatos.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                  },
                  new String [] {
                        "ID", "Tipo", "Precio"
                  }
            ));
            tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        tblDatosMouseClicked(evt);
                  }
            });
            jScrollPane1.setViewportView(tblDatos);

            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(0, 153, 204));
            jLabel1.setText("MANTENIMIENTO DE SERVICIO");

            btnNuevo.setBackground(new java.awt.Color(102, 255, 102));
            btnNuevo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            btnNuevo.setForeground(new java.awt.Color(0, 204, 51));
            btnNuevo.setText("Nuevo");
            btnNuevo.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnNuevoActionPerformed(evt);
                  }
            });

            jPanel1.setBackground(new java.awt.Color(153, 204, 255));

            jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(0, 204, 0));
            jLabel2.setText("ID : ");

            jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(0, 204, 0));
            jLabel3.setText("Tipo :");

            jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(0, 204, 0));
            jLabel4.setText("Precio :");

            txtID.setEnabled(false);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                              .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                              .addComponent(txtPrecio)
                              .addComponent(txtTipoServicio))
                        .addContainerGap(20, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel3)
                              .addComponent(txtTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel4)
                              .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
          // TODO add your handling code here:

          double precio = Double.parseDouble(this.txtPrecio.getText());
          String nombre = this.txtTipoServicio.getText();

          clsServicioNube servicio = new clsServicioNube(nombre, precio);

          clsServicioNubeAD conexion = new clsServicioNubeAD();

          conexion.agregar(servicio);
          cargarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
          // TODO add your handling code here:
          Limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

      private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
            // TODO add your handling code here:
            double precio = Double.parseDouble(this.txtPrecio.getText());
            String nombre = this.txtTipoServicio.getText();
            int servicioId = Integer.parseInt(this.txtID.getText());

            clsServicioNube servicio = new clsServicioNube(servicioId, nombre, precio);
            clsServicioNubeAD conexion = new clsServicioNubeAD();

            conexion.modificar(servicio);
            cargarDatos();
      }//GEN-LAST:event_btnModificarActionPerformed

      private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
            // TODO add your handling code here:
            int filaSel = tblDatos.getSelectedRow();

            txtID.setText(modelo.getValueAt(filaSel, 0).toString());
            txtTipoServicio.setText(modelo.getValueAt(filaSel, 1).toString());
            txtPrecio.setText(modelo.getValueAt(filaSel, 2).toString());

            btnGuardar.setEnabled(false);
            btnModificar.setEnabled(true);
            btnNuevo.setEnabled(true);
      }//GEN-LAST:event_tblDatosMouseClicked

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(dlgServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(dlgServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(dlgServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(dlgServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the dialog */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        dlgServicio dialog = new dlgServicio(new javax.swing.JFrame(), true);
                        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                              @Override
                              public void windowClosing(java.awt.event.WindowEvent e) {
                                    System.exit(0);
                              }
                        });
                        dialog.setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btnGuardar;
      private javax.swing.JButton btnModificar;
      private javax.swing.JButton btnNuevo;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JTable tblDatos;
      private javax.swing.JTextField txtID;
      private javax.swing.JTextField txtPrecio;
      private javax.swing.JTextField txtTipoServicio;
      // End of variables declaration//GEN-END:variables
}
