/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidades.clsUsuario;
import accesoDatos.clsUsuarioAD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ivans
 */
public class dlgUsuario extends javax.swing.JDialog {

      /**
       * Creates new form dlgUsuario
       */
      DefaultTableModel modelo;
      String[] titulos = {"ID", "Nombre", "Email", "Contraseña", "Telefono"};

      public dlgUsuario(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            initComponents();
            modelo = new DefaultTableModel(null, titulos);
            tblDatos.setModel(modelo);
            cargarDatos();
      }

      private void cargarDatos() {

            while (modelo.getRowCount() > 0) {
                  modelo.removeRow(0);
            }

            ArrayList<clsUsuario> lista;
            clsUsuarioAD userAD = new clsUsuarioAD();

            try {
                  lista = userAD.listado();
                  for (clsUsuario user : lista) {
                        String fila[] = {user.getIdUsuario() + "", user.getNombre(), user.getEmail(), user.getContraseña(), user.getTelefono()};
                        modelo.addRow(fila);
                  }
            } catch (Exception e) {
                  JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }

            btnGuardar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnNuevoUsuario.setEnabled(true);

      }

      private void Limpiar() {
            txtContraseña.setText("");
            txtEmail.setText("");
            txtID.setText("");
            txtNombre.setText("");
            txtTelefono.setText("");

            btnGuardar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnNuevoUsuario.setEnabled(true);
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            btnNuevoUsuario = new javax.swing.JButton();
            jPanel1 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            txtID = new javax.swing.JTextField();
            txtNombre = new javax.swing.JTextField();
            txtEmail = new javax.swing.JTextField();
            txtTelefono = new javax.swing.JTextField();
            txtContraseña = new javax.swing.JPasswordField();
            jScrollPane1 = new javax.swing.JScrollPane();
            tblDatos = new javax.swing.JTable();
            btnGuardar = new javax.swing.JButton();
            btnModificar = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(0, 153, 204));
            jLabel1.setText("MANTENIMIENTO DE USUARIO");

            btnNuevoUsuario.setBackground(new java.awt.Color(102, 255, 102));
            btnNuevoUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            btnNuevoUsuario.setForeground(new java.awt.Color(0, 204, 51));
            btnNuevoUsuario.setText("Nuevo");
            btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnNuevoUsuarioActionPerformed(evt);
                  }
            });

            jPanel1.setBackground(new java.awt.Color(153, 204, 255));

            jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(0, 204, 0));
            jLabel2.setText("ID : ");

            jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(0, 204, 0));
            jLabel3.setText("Contraseña :");

            jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(0, 204, 0));
            jLabel4.setText("Nombre :");

            jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(0, 204, 0));
            jLabel5.setText("E-mail :");

            jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(0, 204, 0));
            jLabel6.setText("Telefono :");

            txtID.setEditable(false);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                              .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                              .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                              .addComponent(txtContraseña))
                        .addContainerGap(20, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel3)
                              .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabel4)
                              .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabel5)
                              .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabel6)
                              .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            tblDatos.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                  },
                  new String [] {
                        "ID", "Contraseña", "E-mail", "Telefono"
                  }
            ));
            tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        tblDatosMouseClicked(evt);
                  }
            });
            jScrollPane1.setViewportView(tblDatos);

            btnGuardar.setBackground(new java.awt.Color(102, 255, 102));
            btnGuardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            btnGuardar.setForeground(new java.awt.Color(0, 204, 51));
            btnGuardar.setText("Guardar");
            btnGuardar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnGuardarActionPerformed(evt);
                  }
            });

            btnModificar.setBackground(new java.awt.Color(102, 255, 102));
            btnModificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            btnModificar.setForeground(new java.awt.Color(0, 204, 51));
            btnModificar.setText("Modificar");
            btnModificar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnModificarActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addComponent(jLabel1)
                                    .addGap(0, 0, Short.MAX_VALUE))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                          .addComponent(btnNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed

          Limpiar();

    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
          // TODO add your handling code here:
          String email = this.txtEmail.getText();
          String nombre = this.txtNombre.getText();
          String contraseña = this.txtContraseña.getText();

          String telefono = this.txtTelefono.getText();
          clsUsuario user = new clsUsuario(email, nombre, contraseña, telefono);

          clsUsuarioAD conexion = new clsUsuarioAD();
          conexion.agregar(user);
          cargarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

      private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
            // TODO add your handling code here:
            int userId = Integer.parseInt(this.txtID.getText());
            String email = this.txtEmail.getText();
            String nombre = this.txtNombre.getText();
            String contraseña = this.txtContraseña.getText();

            String telefono = this.txtTelefono.getText();
            clsUsuario user = new clsUsuario(userId, email, nombre, contraseña, telefono);

            clsUsuarioAD conexion = new clsUsuarioAD();
            conexion.modificar(user);
            cargarDatos();
      }//GEN-LAST:event_btnModificarActionPerformed

      private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
            // TODO add your handling code here:
            int filaSel = tblDatos.getSelectedRow();

            txtID.setText(modelo.getValueAt(filaSel, 0).toString());

            txtNombre.setText(modelo.getValueAt(filaSel, 1).toString());
            txtEmail.setText(modelo.getValueAt(filaSel, 2).toString());
            txtContraseña.setText(modelo.getValueAt(filaSel, 3).toString());
            txtTelefono.setText(modelo.getValueAt(filaSel, 4).toString());

            btnGuardar.setEnabled(false);
            btnModificar.setEnabled(true);
            btnNuevoUsuario.setEnabled(true);
      }//GEN-LAST:event_tblDatosMouseClicked

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(dlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(dlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(dlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(dlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the dialog */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        dlgUsuario dialog = new dlgUsuario(new javax.swing.JFrame(), true);
                        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                              @Override
                              public void windowClosing(java.awt.event.WindowEvent e) {
                                    System.exit(0);
                              }
                        });
                        dialog.setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btnGuardar;
      private javax.swing.JButton btnModificar;
      private javax.swing.JButton btnNuevoUsuario;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JTable tblDatos;
      private javax.swing.JPasswordField txtContraseña;
      private javax.swing.JTextField txtEmail;
      private javax.swing.JTextField txtID;
      private javax.swing.JTextField txtNombre;
      private javax.swing.JTextField txtTelefono;
      // End of variables declaration//GEN-END:variables
}
